### ISSUE TITLE
AccessViolationException on disposal

### ISSUE THREAD

**Issue by superware** [PcapDotNet/Pcap.Net#102]
Hello,

When disposing the following class, ReceivePackets randomly throws an AccessViolationException. Is this the proper way to stop dumping and dispose, or maybe an internal issue?

Using Pcap.Net.x64 1.0.4.1 and WinPcap 4.1.3.

```
public class MyService : IDisposable
{
	private const string PcapFileExtension = "pcap";
	private List<PacketCommunicator> _communicators = new List<PacketCommunicator>();
	private List<PacketDumpFile> _dumpFiles = new List<PacketDumpFile>();

	public MyService()
	{
		var path = EnvironmentHelper.ExpandPath(Config.Path, true);
		var fileFormat = config.FileNameFormat;

		foreach (var device in LivePacketDevice.AllLocalMachine)
		{
			var fileName = Path.ChangeExtension(Path.Combine(path, string.Format(fileFormat, DateTimeOffset.UtcNow, PathHelper.NormalizeFileName(device.Name))), PcapFileExtension);
			var communicator = device.Open(65536, PacketDeviceOpenAttributes.Promiscuous, 1000);
			var dumpFile = communicator.OpenDump(fileName);

			_communicators.Add(communicator);
			_dumpFiles.Add(dumpFile);

			Task.Run(() =>
			{
				try
				{
					communicator.ReceivePackets(0, dumpFile.Dump);
				}
				catch (Exception ex)
				{
					//log
				}
			});
		}
	}

	public void Dispose()
	{
		/*foreach (var dumpFile in _dumpFiles)
		{
			dumpFile.Flush();
			dumpFile.Dispose();
		}*/

		foreach (var communicator in _communicators)
		{
			communicator.Break();
			communicator.Dispose();
		}
	}
}
```

**Comment by bricknerb** [comment]
Can you provide more details like the full callstack?
Is your program single threaded?

**Comment by superware** [comment]
Sorry, you are right. And yes, ReceivePackets is on a different thread, Dispose is being called from the main thread.

```
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at pcap_loop(pcap* , Int32 , IntPtr , Byte* )
   at PcapDotNet.Core.PacketCommunicator.ReceivePackets(Int32 count, HandlePacket callback) in c:\github\pcap.net\pcapdotnet\src\pcapdotnet.core\packetcommunicator.cpp:line 181
   at Test.MyService.<>c__DisplayClass4_0.<.ctor>b__0() in D:\Users\superware\Documents\Visual Studio 2017\Projects\Test\Services\MyService.cs:line 46
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by bricknerb** [comment]
You should probably add some synchronization when handling the communicator and the dump files as they are not thread safe.

**Comment by superware** [comment]
Since communicator.ReceivePackets is blocking, it must be called on a different thread. How would you suggest breaking/disposing all receiving communicators?

**Comment by superware** [comment]
@bricknerb? :-)

**Comment by bricknerb** [comment]
Can you dispose the communicator right after the call to ReceivePackets() ?

**Comment by superware** [comment]
The following seems to dispose without throwing, thanks!

Should dumpFile be explicitly disposed?

```
public class MyService : IDisposable
{
	private const string PcapFileExtension = "pcap";
	private List<PacketCommunicator> _communicators = new List<PacketCommunicator>();

	public MyService()
	{
		var path = EnvironmentHelper.ExpandPath(Config.Path, true);
		var fileFormat = config.FileNameFormat;

		foreach (var device in LivePacketDevice.AllLocalMachine)
		{
			var fileName = Path.ChangeExtension(Path.Combine(path, string.Format(fileFormat, DateTimeOffset.UtcNow, PathHelper.NormalizeFileName(device.Name))), PcapFileExtension);
			var communicator = device.Open(65536, PacketDeviceOpenAttributes.Promiscuous, 1000);
			var dumpFile = communicator.OpenDump(fileName);

			_communicators.Add(communicator);

			Task.Run(() =>
			{
				try
				{
					communicator.ReceivePackets(0, dumpFile.Dump);
					communicator.Dispose();
					//dumpFile.Dispose();
				}
				catch (Exception ex)
				{
					//log
				}
			});
		}
	}

	public void Dispose()
	{
		foreach (var communicator in _communicators)
		{
			communicator.Break();
		}
	}
}
```
